spring:
    application:
        name: JH LoginAPI
    messages:
        encoding: UTF-8
    h2:
        console:
            enabled: true
            path: /h2-console
    datasource:
        driver-class-name: org.h2.Driver
        url: "jdbc:h2:mem:spring_assignments;MODE=MYSQL;"
        username: sa
        password:
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: H2_DB
    sql:
        init:
            platform: h2
server:
    port: 7777